### ISSUE TITLE
Transparent images generate weird output with lego options

### ISSUE THREAD

**Issue by KonradLinkowski** [KonradLinkowski/Dotter#2]
Transparent blocks in the lego options should be fully invisible

dots | lego
--- | ---
![tran-dots](https://user-images.githubusercontent.com/26126510/136554020-8d50f57b-3242-4985-8093-158268817f45.png) | ![trans-lego](https://user-images.githubusercontent.com/26126510/136554016-a09c0a02-be1a-4191-aaae-7fd59b0a3263.png)

**Comment by ifa-s** [comment]
Could you assign this to me?

**Comment by KonradLinkowski** [comment]
> Could you assign this to me?

@SingedSimp  sorry, I can't because I already did this.
